language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
bundler_args: --without development
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
before_install: 
  - cp config/database.travis.yml config/database.yml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
